"""Add configurable business hours per day of week."""

from __future__ import annotations

from collections.abc import Sequence
from datetime import time

import sqlalchemy as sa
from alembic import op

revision: str = "20260825_0005"
down_revision: str | None = "20260824_0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "business_hours",
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("is_closed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("day_of_week BETWEEN 0 AND 6", name="ck_business_hours_day_range"),
        sa.CheckConstraint(
            "is_closed OR end_time > start_time", name="ck_business_hours_valid_interval"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("day_of_week", name="uq_business_hours_day"),
    )
    # ### end Alembic commands ###

    # Seed default hours: Monday-Friday 09:00-18:00, Saturday-Sunday closed.
    business_hours_table = sa.table(
        "business_hours",
        sa.column("id", sa.String(36)),
        sa.column("day_of_week", sa.Integer),
        sa.column("start_time", sa.Time),
        sa.column("end_time", sa.Time),
        sa.column("is_closed", sa.Boolean),
    )
    def _row(day: int, closed: bool) -> dict:
        return {
            "id": f"00000000-0000-0000-0000-00000000000{day}",
            "day_of_week": day,
            "start_time": time(9, 0),
            "end_time": time(18, 0),
            "is_closed": closed,
        }

    op.bulk_insert(
        business_hours_table,
        [
            _row(0, False),
            _row(1, False),
            _row(2, False),
            _row(3, False),
            _row(4, False),
            _row(5, True),
            _row(6, True),
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_hours')
    # ### end Alembic commands ###
